# -*- coding: utf-8 -*-
"""AI Spam Email Detection System.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1m-krcj-PHWmYVqutXagp3Rgwz4WpENAK
"""

import pandas as pd
import numpy as np
import re
import nltk

from sklearn.model_selection import train_test_split
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics import accuracy_score
from sklearn.metrics import classification_report
from sklearn.metrics import confusion_matrix
from sklearn.naive_bayes import MultinomialNB

import seaborn as sns
import matplotlib.pyplot as plt

nltk.download("stopwords")

from nltk.corpus import stopwords

data = {
"text":[
"Win money now",
"Lowest price pharmacy",
"Hi how are you",
"Let's meet tomorrow",
"Claim your free prize",
"Important update about account",
"Cheap loans available",
"Project meeting at 5",
"Congratulations you won lottery",
"Dinner tonight?"
],
"label":[
"spam",
"spam",
"ham",
"ham",
"spam",
"ham",
"spam",
"ham",
"spam",
"ham"
]
}

df = pd.DataFrame(data)

print(df)

stop_words = set(stopwords.words("english"))

def preprocess(text):

    text = text.lower()

    text = re.sub("[^a-zA-Z]"," ",text)

    words = text.split()

    words = [word for word in words if word not in stop_words]

    return " ".join(words)

df["clean_text"] = df["text"].apply(preprocess)

print(df)

X = df["clean_text"]
y = df["label"]

vectorizer = TfidfVectorizer()

X_vector = vectorizer.fit_transform(X)

X_train,X_test,y_train,y_test = train_test_split(
    X_vector,y,test_size=0.3,random_state=42
)

model = MultinomialNB()

model.fit(X_train,y_train)

pred = model.predict(X_test)

accuracy = accuracy_score(y_test,pred)

print("Accuracy:",accuracy)

print(classification_report(y_test,pred))

cm = confusion_matrix(y_test,pred)

sns.heatmap(cm,annot=True,fmt="d")
plt.title("Confusion Matrix")
plt.show()

print("Test your own message")

msg = input("Enter message: ")

msg = preprocess(msg)

msg_vec = vectorizer.transform([msg])

prediction = model.predict(msg_vec)

print("Prediction:",prediction[0])

